spring:
  application:
    name: learn-service
  datasource:
    url: jdbc:postgresql://localhost:5432/learn-service-db
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    hikari:
      data-source-properties:
        reWriteBatchedInserts: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_ISSUER_URI}
          audiences: ${OAUTH2_AUDIENCE}
  threads:
    virtual:
      enabled: true

openai:
  api-key: ${OPENAI_API_KEY}
